#!/bin/bash

reinstalar () {
apt-get update -y
apt-get upgrade -y
wget -c -P /bin https://raw.githubusercontent.com/Leonn34/script-2/master/setup.sh
chmod +x /bin/setup.sh
bash /bin/setup.sh
}

remove () {
echo -e ""
echo -e ""
rm /bin/criarusuario >/dev/null 2>/dev/null
rm /bin/expcleaner >/dev/null 2>/dev/null
rm /bin/sshlimiter >/dev/null 2>/dev/null
rm /bin/addhost >/dev/null 2>/dev/null
rm /bin/delhost >/dev/null 2>/dev/null
rm /bin/sshmonitor >/dev/null 2>/dev/null
rm /bin/ajuda >/dev/null 2>/dev/null
rm /bin/menu >/dev/null 2>/dev/null
rm /bin/atualizar >/dev/null 2>/dev/null
rm /bin/clearcache >/dev/null 2>/dev/null
rm /bin/badudp >/dev/null 2>/dev/null
rm /bin/userbkp >/dev/null 2>/dev/null
rm /bin/socks.py >/dev/null 2>/dev/null
rm /bin/setup.sh >/dev/null 2>/dev/null
rm /bin/att >/dev/null 2>/dev/null
rm /bin/ver >/dev/null 2>/dev/null
rm /bin/ver1 >/dev/null 2>/dev/null
rm /bin/testeconexao >/dev/null 2>/dev/null
rm /bin/speedtest.py >/dev/null 2>/dev/null

ssh="/etc/ssh/sshbak"
if [ ! -f "$ssh" ]
then
  echo ""
else
mv -f /etc/ssh/sshbak /etc/ssh/sshd_config
fi
apt-get remove squid3 -y 1>/dev/null 2>/dev/null apt-get remove squid -y 1>/dev/null 2>/dev/null apt-get autoremove -y 1>/dev/null 2>/dev/null
}

echo -e "\033[1;31mDESINSTALAR OU INSTALAR OUTRO GERENCIADOR?"
echo -e "[1] DESINSTALAR
[2] INSTALAR OUTRO GERENCIADOR\033[0m"
read -p ": " resposta
case $resposta in
 2)
remove
reinstalar
exit
;;
 *)
remove
exit
;;
esac
exit